import { Resend } from 'resend';
import { config } from '../config/env.js';
import { IUser } from '../models/User.js';
import { DigestContent } from './digestGenerator.js';
import { logError } from '../config/logger.js';

let resend: Resend | null = null;

function getResend() {
  if (!resend && config.RESEND_API_KEY) {
    resend = new Resend(config.RESEND_API_KEY);
  }
  return resend;
}

export async function sendMagicLinkEmail(email: string, magicLink: string): Promise<boolean> {
  const client = getResend();
  if (!client) return false;

  const html = renderMagicLinkHtml(magicLink);

  try {
    await client.emails.send({
      from: config.EMAIL_FROM,
      to: email,
      subject: 'Your Magic Link to Quirk',
      html,
    });
    return true;
  } catch (error) {
    logError(`MAGIC LINK email failed for ${email}`, { err: error as Error });
    return false;
  }
}

function renderMagicLinkHtml(magicLink: string): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: Georgia, serif; background: #F5F0E8; color: #2D2D2D; padding: 20px; }
    .container { max-width: 600px; margin: 0 auto; background: #FDFBF7; border: 3px solid #1A1A1A; border-radius: 12px; padding: 32px; }
    h1 { font-family: 'Courier New', monospace; text-transform: uppercase; font-size: 24px; margin-bottom: 8px; }
    .link { display: inline-block; background: #E8725C; color: #FDFBF7; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-family: monospace; font-weight: bold; text-transform: uppercase; border: 2px solid #1A1A1A; margin: 16px 0; }
    .footer { margin-top: 32px; font-size: 12px; color: #6B6B6B; text-align: center; }
  </style>
</head>
<body>
  <div class="container">
    <h1>QUIRK</h1>
    <p>Click the button below to create your account:</p>
    <a href="${magicLink}" class="link">CREATE ACCOUNT</a>
    <p style="font-size: 12px; color: #6B6B6B;">Or copy this link: ${magicLink}</p>
    <div class="footer">Generated by Quirk</div>
  </div>
</body>
</html>`;
}

export async function sendDigestEmail(user: IUser, digest: DigestContent): Promise<boolean> {
  const client = getResend();
  if (!client) return false;

  const html = renderDigestHtml(user, digest);

  try {
    await client.emails.send({
      from: config.EMAIL_FROM,
      to: user.email,
      subject: 'Your Daily LinkedIn Content is Ready',
      html,
    });
    return true;
  } catch (error) {
    logError(`EMAIL digest send failed for ${user.email}`, { err: error as Error });
    return false;
  }
}

function renderDigestHtml(user: IUser, digest: DigestContent): string {
  const name = user.email.split('@')[0];

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: Georgia, serif; background: #F5F0E8; color: #2D2D2D; padding: 20px; }
    .container { max-width: 600px; margin: 0 auto; background: #FDFBF7; border: 3px solid #1A1A1A; border-radius: 12px; padding: 32px; }
    h1 { font-family: 'Courier New', monospace; text-transform: uppercase; font-size: 24px; margin-bottom: 8px; }
    h2 { font-family: 'Courier New', monospace; text-transform: uppercase; font-size: 16px; color: #E8725C; margin-top: 24px; }
    .post { background: #F5F0E8; border-radius: 8px; padding: 16px; margin: 12px 0; font-size: 14px; line-height: 1.6; }
    .cta { display: inline-block; background: #E8725C; color: #FDFBF7; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-family: monospace; font-weight: bold; text-transform: uppercase; border: 2px solid #1A1A1A; }
    .footer { margin-top: 32px; font-size: 12px; color: #6B6B6B; text-align: center; }
  </style>
</head>
<body>
  <div class="container">
    <h1>QUIRK</h1>
    <p>Your daily LinkedIn content, ${name}.</p>

    <h2>Text Posts</h2>
    ${digest.textPosts.map((post: string) => `<div class="post">${post.replace(/\n/g, '<br>')}</div>`).join('')}

    <h2>Carousel</h2>
    <div class="post">
      ${Array.isArray(digest.carousel) 
        ? digest.carousel.map((slide: Record<string, unknown>, i: number) => `<strong>${(slide.heading as string) || `Slide ${i+1}`}</strong><br>${(slide.body as string) || ''}`).join('<br><br>')
        : 'Carousel content'}
    </div>

    <h2>Image Prompt</h2>
    <div class="post">${digest.imagePrompt}</div>

    <div style="text-align: center; margin-top: 24px;">
      <a href="http://localhost:5173/dashboard" class="cta">VIEW IN DASHBOARD</a>
    </div>

    <div class="footer">
      Generated by Quirk
    </div>
  </div>
</body>
</html>`;
}
